alura/techguide

README.md

Update Release links to main project releases page.

:wrench: Change link releases (#16)

---

_data/blocks/apollo-client.pt_BR.yaml
_data/blocks/graphql.pt_BR.yaml
_data/blocks/nestjs-fundamentals.pt_BR.yaml
_data/blocks/nodejs-authentication-tokens.pt_BR.yaml
_data/blocks/nodejs-fundamentals.pt_BR.yaml
_data/blocks/nodejs-testing.pt_BR.yaml
_data/blocks/typescript-fundamentals.pt_BR.yaml
_data/blocks/websockets.pt_BR.yaml

Adição de textos e modificação de links de conteúdo de node.js

add: node content

---

CONTRIBUTING.md
STRUCTURE.md
src/patterns/ScreenHeroContainer/patterns/GuidesGrid/index.tsx

Pontos importantes para o projeto e para facilitar a contribuição externa

docs: add initial docs and home refactor

---

src/theme/GlobalStyle.tsx

Na issue #29, o @TaylorNAlbarnaz sugeriu que ao clicar em "Selecionar minha carreira!", ocorra uma animação ao navegar para o topo da página, ou seja, que o scroll seja mais suave.
Pois, no momento, a navegação ocorre de forma "seca", assim:
https://user-images.githubusercontent.com/57193392/192577345-b7654c01-be4e-4396-97ab-b5d60877d87e.mp4
Na issue, o @marco-beduschi deu uma sugestão de implementação muito massa :heart_eyes: que consiste em substituir o `<Link />` por um `<Button />` e manipular o scroll via JavaScript, setando o `behavior: 'smooth'`, no método `window.scroll()`. E, em resumo, a mágica aconteceria no `onClick` do botão.
Seguindo essa abordagem, fui entender onde ocorreria a substituição de fato e daí partiria para implementação. 
E ocorreria em 2 pontos:
1. No `Link` na …

feat: smooth scroll

---

_api/infra/storage/index.ts
_api/modules/blocks/repository.ts
_api/modules/guides/repository.ts

Example of how much the speed was increasing by using more memory instead of multiple reads in disk

feat: improve build time by using more memory instead of multiple IOs

---

_data/blocks/pt_BR/php-composer.pt_BR.yaml
_data/blocks/pt_BR/php-functional.pt_BR.yaml
_data/blocks/pt_BR/php-fundamentals.pt_BR.yaml

Links ajustados para abrir direto a página do curso quando o usuário estiver logado.
Cursos:
- PHP Composer: Dependências, Autoload e Publicação
- PHP: Programação Funcional
- PHP: conceitos, lidando com dados, loops e mais
- PHP Strings: manipulando textos com PHP
- Formação PHP

Ajuste nos links de alguns cursos de PHP

---

_api/api.ts
_api/gql_types.ts
_api/modules/blocks/repository.ts
_api/modules/guides/repository.ts
_data/locale/es.json
pages/es/index.tsx
pages/es/path/[slug]/[activeBlockSlug].tsx
pages/es/path/[slug]/index.tsx
pages/index.tsx
pages/pt-BR/index.tsx
pages/pt-BR/path/[slug]/index.tsx
src/components/Link/index.tsx
src/gql_types.ts
src/infra/i18n/withLocaleContent.ts
src/screens/HomeScreen/patterns/GuidesGrid/index.tsx

This PR enable the ES version in the /es URL

feat: enable es version

---

_data/blocks/pt_BR/java-error-handling.pt_BR.yaml
_data/blocks/pt_BR/java-errorhandling.pt_BR.yaml

Adding a new article suggestion about Java Error Handling

Adding a new article suggestion about Java Error Handling

---

_data/blocks/pt_BR/solid.pt_BR.yaml

Adicionando o livro que lancei pela Casa do Código, o Desbravando SOLID, como referência no block de SOLID.

SOLID: adiciona livro Desbravando SOLID

---

_data/blocks/pt_BR/big-data-and-data-engineering.pt_BR.yaml
_data/blocks/pt_BR/computer-vision.pt_BR.yaml
_data/blocks/pt_BR/data-extraction-and-processing.pt_BR.yaml
_data/blocks/pt_BR/data-science-fundamentals.pt_BR.yaml
_data/blocks/pt_BR/deep-learning.pt_BR.yaml
_data/blocks/pt_BR/feature-engineering.pt_BR.yaml
_data/blocks/pt_BR/jupyter-colaboratory.pt_BR.yaml
_data/guides/pt_BR/data-scientist.yaml

Pontos a serem alterados, sugeridos pelo Paulo durante a gravação do hipsters. (Solicitação do Fabrício)

Alterações de Data Science no Tech Guide

---

_data/blocks/es/big-data-and-data-engineering.yaml
_data/blocks/es/business-intelligence.yaml
_data/blocks/es/business-process-management.yaml
_data/blocks/es/cloud-fundamentals-data-science.yaml
_data/blocks/es/communication-skills.yaml
_data/blocks/es/computer-vision.yaml
_data/blocks/es/data-extraction-and-processing.yaml
_data/blocks/es/data-science-fundamentals.yaml
_data/blocks/es/data-visualization.yaml
_data/blocks/es/deep-learning.yaml
_data/blocks/es/excel.yaml
_data/blocks/es/feature-engineering.yaml
_data/blocks/es/git-and-github-fundamentals-data-science.yaml
_data/blocks/es/jupyter-and-colab.yaml
_data/blocks/es/linux-fundamentals.yaml
_data/blocks/es/machine-learning-fundamentals.yaml
_data/blocks/es/machine-learning-model-evaluation.yaml
_data/blocks/es/machine-learning-unsupervised-learning.yaml
_data/blocks/es/natural-language-processing.yaml
_data/blocks/es/python-for-data-science.yaml
_data/blocks/es/r-for-data-science.yaml
_data/blocks/es/reinforcement-learning.yaml
_data/blocks/es/sql-fundamentals.yaml
_data/blocks/es/statistical-tests.yaml
_data/blocks/es/statistics-and-math-fundamentals.yaml
_data/blocks/es/storytelling-with-data.yaml
_data/blocks/es/web-scraping.yaml
_data/guides/es/data-scientist.yaml

Foi criado o guide em espanhol para a página do tech guide latam de ciência de dados, juntamente com os blocks com os conteúdos obtidos na curadoria. Este tech guide latam foi baseado no tech guide pt-br, logo, também possui 27 cards de conteúdo. Esse PR lança o guide e os 27 blocks.

Criação do Guide e Blocks do Tech Guide Latam de Data Science

---

_data/blocks/pt_BR/cloud-fundamentals.pt_BR.yaml
_data/blocks/pt_BR/containers.pt_BR.yaml
_data/blocks/pt_BR/data-structures.pt_BR.yaml
_data/blocks/pt_BR/design-patterns.pt_BR.yaml
_data/blocks/pt_BR/java-collections.pt_BR.yaml
_data/blocks/pt_BR/java-testing.pt_BR.yaml
_data/blocks/pt_BR/jvm.pt_BR.yaml
_data/blocks/pt_BR/microservices.pt_BR.yaml
_data/downloadFiles/EN_US/angular.md
_data/downloadFiles/EN_US/flutter.md
_data/downloadFiles/EN_US/front-end.md
_data/downloadFiles/EN_US/java.md
_data/downloadFiles/EN_US/nodejs.md
_data/downloadFiles/EN_US/react.md
_data/downloadFiles/PT_BR/angular.md
_data/downloadFiles/PT_BR/csharp.md
_data/downloadFiles/PT_BR/data-scientist.md
_data/downloadFiles/PT_BR/flutter.md
_data/downloadFiles/PT_BR/front-end.md
_data/downloadFiles/PT_BR/java.md
_data/downloadFiles/PT_BR/nodejs.md
_data/downloadFiles/PT_BR/php.md
_data/downloadFiles/PT_BR/python.md
_data/downloadFiles/PT_BR/react.md

Correção de algumas inconsitências nos links para os conteúdos dos guide de Java.
As inconsistências foram relatadas nas seguintes issues:
- #94 
- #95

Reviews links conteúdos guide Java

---

_data/downloadFiles/PT_BR/android.md

De acordo com a issue relatada em: #112, observei que o erro era causado pela falta do arquivo `android.md` na estrutura para downloads.
Criei o arquivo seguindo a estrutura do path já estipulado.

Fix: android path download

---

_data/downloadFiles/PT_BR/flutter.md

Acentuando palavra Nível e completando Pull no request

Docs: 2ª Text Correction

---

_data/downloadFiles/PT_BR/android.md

- Acentuando palavras - Nivel _**(Nível)**_
- Completado frase - Pul (**Pull** request)
apartir **_(A forma correta é a partir)_**
oturas - **_(A forma correta é: outras)_**
executararem - **_(A forma correta é: executarem)_**
bibliteocas - **_(A forma correta é: bibliotecas)_**
compormentos - **_(A forma correta é: comportamentos)_**
analizador **_(A forma correta é: analisador)_** 
- **Text Style**

Docs: Text Style and Correction

---

_data/locale/en-US.ts
_data/locale/es.ts
_data/locale/pt-BR.ts
pages/en-US/my.tsx
pages/es/my.tsx
pages/pt-BR/my.tsx

Adding a transition screen when creating a custom guide

feat: generate your guide

---

_data/downloadFiles/PT_BR/angular.md

Correção de erros ortográficos

Docs: Text Correction

---

_data/downloadFiles/PT_BR/cybersecurity.md

Update cybersecurity guide

---

_data/cards/pt_BR/jupyter-and-colaboratory.yaml

Esse artigo inclui algumas dicas interessantes para trabalhar com Jupyter Notebook e está no Medium da comunidade do Data Hackers.
Talvez seja interessante a inclusão, principalmente no primeiro nível do T de Data Science.
Maximize sua eficiência: 10 passos para organizar seu Jupyter Notebook
https://medium.com/data-hackers/maximize-sua-eficiência-10-passos-para-organizar-seu-jupyter-notebook-522b4bdf8261

Updating Jupyter e Colab - Data Science

---

_data/downloadFiles/EN_US/android.md
_data/downloadFiles/EN_US/angular.md
_data/downloadFiles/EN_US/csharp.md
_data/downloadFiles/EN_US/cybersecurity.md
_data/downloadFiles/EN_US/data-science.md
_data/downloadFiles/EN_US/flutter.md
_data/downloadFiles/EN_US/front-end.md
_data/downloadFiles/EN_US/java.md
_data/downloadFiles/EN_US/nodejs.md
_data/downloadFiles/EN_US/php.md
_data/downloadFiles/EN_US/python.md
_data/downloadFiles/EN_US/react.md

fixes https://github.com/alura/techguide/issues/86
In this PR
- Update the EN_US docs from `Nível` to `Level`
- Update the EN_US docs from `Habilidade Auxiliar` to `Additional Skill` (lmk if this translation key is ok)

Replace Portuguese words with English ones for the EN_US guides

---

pages/_document.tsx

It adds canonical URL to each page and fixes https://github.com/alura/techguide/issues/127

Add canonical URL tag

---

_data/guides/pt_BR/full-stack.yaml

First draft of the fullstack guide, focused mainly on a React/Node.js stack.

add: fullstack guide

---

_data/cards/pt_BR/api_building.yaml
_data/cards/pt_BR/big-data-principles.yaml
_data/cards/pt_BR/business-intelligence-fundamentals.yaml
_data/cards/pt_BR/cloud-fundamentals.yaml
_data/cards/pt_BR/container-management.yaml
_data/cards/pt_BR/data-engineering-fundamentals.yaml
_data/cards/pt_BR/data-extraction-and-processing.yaml
_data/cards/pt_BR/data-governance.yaml
_data/cards/pt_BR/data-lakes.yaml
_data/cards/pt_BR/data-mesh.yaml
_data/cards/pt_BR/data-pipeline-orchestration.yaml
_data/cards/pt_BR/data-pipelines-deploy.yaml
_data/cards/pt_BR/data-warehouses.yaml
_data/cards/pt_BR/databases-fundamentals.yaml
_data/cards/pt_BR/devops-and-cloud-concepts.yaml
_data/cards/pt_BR/distributed-data-processing.yaml
_data/cards/pt_BR/infrastructure_as_code.yaml
_data/cards/pt_BR/log-management.yaml
_data/cards/pt_BR/mlops.yaml
_data/cards/pt_BR/nosql-databases.yaml
_data/cards/pt_BR/pipelines-and-etl.yaml
_data/cards/pt_BR/relational-databases.yaml
_data/cards/pt_BR/software_testing.yaml
_data/cards/pt_BR/streaming.yaml
_data/guides/pt_BR/data-engineering.yaml

Adicionando os cards para o Tech Guide de Engenharia de Dados. Também adicionamos conteúdos a 3 outros cards já existentes: cloud-fundamentals, business-intelligence-fundamentals e data-extraction-and-processing.

add data-engineering guide

---

src/patterns/Footer/index.tsx

Para melhor experiência do usuário, adicionei um link na logo do footer para que o usuário possa voltar para o início da página.

feat: add link in footer logo

---

_data/cards/es/containers.yaml
_data/cards/es/java-fundamentals.yaml
_data/cards/es/java-memory-management.yaml
_data/cards/es/java-spring-boot.yaml
_data/cards/es/java-spring-framework.yaml
_data/cards/es/kafka.yaml
_data/cards/es/object-oriented.yaml
_data/cards/es/oop-concepts.yaml

Tech Guide Latam Java
Foram realizadas melhorias nos seguintes 7 cards:
- containers.yaml
- java-fundamentals.yaml
- java-memory-management.yaml
- java-spring-boot.yaml
- java-spring-framework.yaml
- kafka.yaml
- object-oriented.yaml
As melhorias foram feitas focadas em adicionar conteúdos ou ajustar texto/link errado nos cards.

Tech Guide Latam Java - Melhorias

---

_data/cards/pt_BR/human-interface-guidelines.yaml
_data/cards/pt_BR/ios-animations.yaml
_data/cards/pt_BR/ios-app-resources.yaml
_data/cards/pt_BR/ios-architectures.yaml
_data/cards/pt_BR/ios-asynchronous.yaml
_data/cards/pt_BR/ios-debugging.yaml
_data/cards/pt_BR/ios-deployment.yaml
_data/cards/pt_BR/ios-external-requests.yaml
_data/cards/pt_BR/ios-persistence.yaml
_data/cards/pt_BR/ios-swiftui.yaml
_data/cards/pt_BR/ios-system-resources.yaml
_data/cards/pt_BR/ios-third-libraries.yaml
_data/cards/pt_BR/objective-c-fundamentals.yaml
_data/cards/pt_BR/swift-fundamentals.yaml
_data/guides/pt_BR/ios.yaml

- Fix: links quebrados
- Adição de conteúdos

Correções iOS

---

_data/cards/pt_BR/kotlin-asynchronous.yaml
_data/cards/pt_BR/kotlin-dependency-injection.yaml
_data/cards/pt_BR/solid.yaml

Adicionei alguns videos que eu fiz no meu canal do youtube CodandoTV sobre esses 3 itens.
- SOLID
- Koin
- Configuração de networking

Adicionando videos do SOLID, Koin e Configuração de networking para o techguide Android

---

_data/cards/pt_BR/ios-app-modularization.yaml
_data/cards/pt_BR/ios-state-manager.yaml
_data/cards/pt_BR/ios-storyboards.yaml
_data/cards/pt_BR/ios-swiftui.yaml
_data/cards/pt_BR/ios-system-resources.yaml
_data/cards/pt_BR/ios-third-libraries.yaml
_data/cards/pt_BR/swift-fundamentals.yaml
_data/cards/pt_BR/xcode.yaml

Added more content for:
- Modularization
- State manager
- Storyboards
- SwiftUI
- System Resources
- 3rd Libraries
- Swift
- and Xcode.

Added more content for iOS.

---

_data/cards/pt_BR/ios-viewcode.yaml

**Descrição**
Add new article in View Code
- Adicionei um novo artigo sobre viewcode. Não exclui, apenas adicionei informações seguindo as diretrizes para contribuições.

iosNewFeature

---

_data/cards/pt_BR/react-components.yaml

Nesta pull request, fiz as seguintes modificações:
- Adicionei o curso [React: desenvolvendo com JavaScript](https://cursos.alura.com.br/course/react-desenvolvendo-javascript): Com o objetivo de aprimorar nosso conteúdo relacionado ao desenvolvimento em React, incluí este curso. Ele é a porta de entrada para pessoas que saíram do HTML, CSS e JavaScript que querem aprender React.
- Adicionei o curso [React: como os componentes funcionam](https://www.alura.com.br/curso-online-react-componentes-funcionam): Este curso fornece uma compreensão mais profunda de como os componentes funcionam em React e é uma adição valiosa ao nosso conjunto de recursos.
- Adicionei a formação [Explore React com JavaScript](https://cursos.alura.com.br/formacao-react-javascript): Para proporcionar aos nossos alunos …

fix (React): Atualização dos cursos e recursos sobre componentes em React

---

_data/cards/pt_BR/react-props.yaml

Nesta pull request, foram realizadas as seguintes atualizações:
- Adicionei a formação [Explore React com JavaScript](https://cursos.alura.com.br/formacao-react-javascript): Esta formação é uma adição valiosa para ajudar nossos alunos a explorar o React mais a fundo, incluindo o uso de Props.
- Atualizei o link da imersão React para a versão mais recente: Para manter nossos recursos atualizados, atualizei o link da Imersão React para a versão mais recente.
- Adicionei o curso [React: desenvolvendo com JavaScript](https://cursos.alura.com.br/course/react-desenvolvendo-javascript): Este curso foi adicionado para fornecer aos nossos alunos uma abordagem completa para desenvolver em React com JavaScript, incluindo o uso de Props.
- Removi o curso de styled components: Decidi remover o curso …

fix: Corrige links e adiciona novos conteúdos ao card de react props

---

_data/cards/pt_BR/create-react-app.yaml

Nesta pull request, efetuei as seguintes atualizações:
- Adicionei a formação [Explore React com JavaScript](https://cursos.alura.com.br/formacao-react-javascript): Esta formação é uma adição valiosa para ajudar nossos alunos a explorar o React em profundidade, incluindo a criação de aplicações React.
- Adicionei o curso [React: desenvolvendo com JavaScript](https://cursos.alura.com.br/course/react-desenvolvendo-javascript): Este curso foi incluído para oferecer aos nossos alunos uma abordagem completa para desenvolver aplicações React usando JavaScript.
- Adicionei a formação [Formação Gerencie aplicações React com Typescript](https://www.alura.com.br/formacao-react-ts): Esta formação abrange o gerenciamento de aplicações React com TypeScript e é uma adição importante ao nosso conjunto …

fix: Corrige links, adiciona conteúdos atualizados sobre como criar aplicações React.

---

_data/cards/pt_BR/react-hooks-effect.yaml
_data/cards/pt_BR/react-hooks-state.yaml

Nesta pull request, foram realizadas as seguintes modificações nos cards "React Hooks: State" e "React Hooks: Effect":
- Removi o link do curso de gerenciamento de estados com Context API: Decidi remover este link para concentrar nossos recursos em tópicos mais relevantes relacionados aos Hooks State. Esse conteúdo será adicionado em breve em um card específico.
- Adicionei o curso [React: desenvolvendo com JavaScript](https://cursos.alura.com.br/course/react-desenvolvendo-javascript): Este curso foi incluído para oferecer aos nossos alunos uma abordagem completa para o desenvolvimento de componentes com Hooks State usando JavaScript.
- Corrigi os links da documentação para as versões mais atualizadas: Atualizei os links da documentação do React para garantir que os alunos tenham acesso à …

fix: Corrige links, adiciona conteúdos aos cards de hooks useState e useEffect.

---

_data/cards/pt_BR/react-hooks-callback.yaml
_data/cards/pt_BR/react-hooks-memo.yaml
_data/cards/pt_BR/react-hooks-ref.yaml

Nesta pull request, foram realizadas as seguintes modificações nas seções "React - Memo", "React - Callback" e "React - Ref":
- Removi o link do curso de gerenciamento de estados com Context API: Decidi remover este link para concentrar nossos recursos em tópicos mais relevantes relacionados ao Memo.
- Adicionei o curso [React: otimizando a performance](https://cursos.alura.com.br/course/react-otimizando-performance): Este curso foi incluído para abordar o tópico de otimização de performance em React, o que é relevante ao considerar o Memo.
- Adicionei os links atualizados da documentação: Garanti que os links da documentação estejam atualizados, permitindo que os alunos acessem as informações mais recentes e precisas.
- Adicionei o curso [React: otimizando a …

fix: Corrige links da documentação do react. Adiciona os links mais recentes e conteúdos atualizados em cada card

---

_data/cards/pt_BR/css-in-js.yaml

Nesta pull request, foram realizadas as seguintes modificações na seção "React - CSS-in-JS":
- Adicionei o curso [React: desenvolvendo componentes customizados e acessíveis com Emotion](https://cursos.alura.com.br/course/react-componentes-customizados-acessiveis-emotion): Este curso é uma adição valiosa para aprofundar o conhecimento sobre o uso de Emotion para desenvolver componentes customizados e acessíveis em React.
- Adicionei o artigo [Criando Styled Components Com React](https://blog.matheuscastiglioni.com.br/criando-styled-components-com-react/): Este artigo é uma excelente referência para aprender a criar Styled Components com React.
- Removi o site das aulas iniciais do curso de Styled components: Decidi remover o link para o site das aulas iniciais do curso de Styled components …

fix: Corrige links da documentação. Adiciona artigo de Alura Stars e dois novos cursos sobre o tema

---

_data/cards/pt_BR/react-design-system-libraries.yaml

Nesta pull request, foram realizadas as seguintes modificações na seção "React - Bibliotecas de Design System":
- Removi a formação de Design System de UX: Decidi remover esta formação para manter nosso conteúdo atualizado e relevante.
- Adicionei a [formação de Design System com React](https://cursos.alura.com.br/formacao-next-js-tailwind-design-system): Esta nova formação abrange o tópico de Design System com foco em React, Next js e Tailwind CSS, proporcionando aos nossos alunos uma abordagem mais específica e atualizada.
- Adicionei o curso [React: criando um Design System com TailwindCSS](https://cursos.alura.com.br/course/react-criando-design-system-tailwind): Este curso complementa a formação, ensinando como criar um Design System usando TailwindCSS em React.
Estas modificações têm …

fix: Adiciona conteúdos atualizados referentes ao tema do card

---

_data/cards/pt_BR/frontend-semantic-versioning.yaml

- Adicionei o artigo [Simplificando o controle de versão com Conventional Commits](https://www.alura.com.br/artigos/simplificando-controle-versao-conventional-commits): Este artigo é uma excelente adição à nossa documentação, pois explora como simplificar o controle de versão usando Conventional Commits, uma prática útil em desenvolvimento de software.
- Adicionei o artigo [Versionamento Semântico (SemVer): uma breve introdução](https://www.alura.com.br/artigos/versionamento-semantico-breve-introducao): Este artigo fornece uma introdução ao Versionamento Semântico (SemVer), que é uma prática fundamental para o controle de versão de software.
Estas modificações visam enriquecer nossa documentação, fornecendo informações …

feat: Adiciona artigos recentes sobre versionamento semântico no conteúdo do card

---

_data/cards/pt_BR/redux-saga.yaml

- Adicionei o curso [React: gerenciamento de estados globais com Redux](https://cursos.alura.com.br/course/react-gerenciamento-estados-globais-redux): Este curso é uma adição valiosa ao nosso conteúdo, abordando o gerenciamento de estados globais em React com Redux, incluindo o uso de Redux Saga.
- Adicionei a formação [Gerencie estados em React com Redux](https://cursos.alura.com.br/formacao-react-gestao-estados): Esta formação oferece uma abordagem abrangente para o gerenciamento de estados em React com Redux, cobrindo vários aspectos importantes, incluindo o Redux Saga.
Estas modificações têm como objetivo enriquecer nosso conteúdo relacionado ao Redux Saga, proporcionando aos alunos acesso a recursos abrangentes e …

feat: Adiciona conteúdos relacionado a Redux que estão disponíveis na plataforma

---

_data/cards/pt_BR/react-state-management.yaml
_data/guides/pt_BR/react.yaml

- Criei um novo card intitulado 'React Gerenciamento de Estados': Este card fornece um recurso dedicado para explorar diferentes técnicas de gerenciamento de estados em aplicativos React.
- Adicionei conteúdo à plataforma para o card 'React Gerenciamento de Estados': Foram incluídos tutoriais, artigos e exemplos práticos abordando várias abordagens de gerenciamento de estados em aplicativos React, incluindo Context API, Redux, Recoil e mais. O conteúdo foi projetado para ajudar os desenvolvedores a entender e escolher a melhor estratégia para seus projetos.
Estas modificações têm como objetivo fornecer aos usuários uma fonte valiosa de informações sobre o gerenciamento de estados em React, permitindo-lhes explorar e escolher …

feat: Adiciona um card para os conteúdos de React Gerenciamento de Estados

---

_data/cards/pt_BR/java-collections.yaml
_data/downloadFiles/PT_BR/java.md

Adicionei um artigo detalhando a abstração Stream introduzida no Java 8. O conteúdo aborda a capacidade declarativa do Stream e sua eficiência em arquiteturas de múltiplos núcleos. O artigo também descreve cada uma de suas funções para proporcionar um entendimento aprofundado.

Adicionando um artigo PT-BR, na categoria Java Coleções em como utilizar o Java Streams no Java8+ para manipular Coleções e Mapas

---

_data/cards/en_US/android-monitor.yaml
_data/cards/en_US/android-sec.yaml
_data/cards/en_US/clean-architecture.yaml
_data/cards/en_US/kotlin-asynchronous.yaml
_data/cards/pt_BR/android-accessibility.yaml
_data/cards/pt_BR/android-app-navigation.yaml
_data/cards/pt_BR/android-architecture.yaml
_data/cards/pt_BR/android-image-loading.yaml
_data/cards/pt_BR/android-jetpack-compose-fundamentals.yaml
_data/cards/pt_BR/android-monitor.yaml
_data/cards/pt_BR/android-sec.yaml
_data/cards/pt_BR/clean-architecture.yaml
_data/cards/pt_BR/git-and-github-fundamentals.yaml
_data/cards/pt_BR/kotlin-asynchronous.yaml
_data/cards/pt_BR/kotlin-dependency-injection.yaml
_data/cards/pt_BR/solid.yaml
_data/guides/en_US/android.yaml
_data/guides/pt_BR/android.yaml

- Adicionei alguns videos que eu fiz no meu canal do youtube CodandoTV sobre esses 3 itens.
- Adicionado a sessão de segurança, pois foi comentado no podcast do techguide android 
- Adicionado a sessão de monitoramento, pois foi comentado no podcast do techguide android
OBS: Ainda preciso verificar com o @fabriciocarraro  como validar certinho, então ainda está em análise

Adicionado sessão de Segurança e Monitoramento, e alguns links de conteudo do CodandoTV

---

_data/cards/pt_BR/android-accessibility.yaml

- Olá pessoal, vou começar adicionar o conteúdo que venho produzindo sobre desenvolvimento Android (Jetpack Compose com Rick e Morty)

Adicionando slides sobre Acessibilidade em Compose

---

_data/cards/es/business-intelligence-fundamentals.yaml
_data/cards/es/csharp-fundamentals.yaml
_data/cards/es/data-structures.yaml
_data/cards/es/data-visualization-bi.yaml
_data/cards/es/http-fundamentals.yaml
_data/cards/es/javascript-fundamentals.yaml
_data/cards/es/oop-concepts.yaml
_data/cards/es/python-for-data-science.yaml

Adicionando novos conteúdos tg latam

Adicionando novos conteúdos tg latam

---

_data/cards/en_US/android-accessibility.yaml
_data/cards/en_US/android-gradle.yaml
_data/cards/en_US/android-security-monitoring.yaml
_data/cards/pt_BR/android-accessibility.yaml
_data/cards/pt_BR/android-gradle.yaml
_data/cards/pt_BR/android-security-monitoring.yaml

- Arrumando o link de acessibilidade que coloquei anteriormente para que possa ser acessado o meu repositório de slides;
- Adicionando conteúdos sobre: Gradle e Segurança;
- Adicionando a versão inglês de conteúdo de acessibilidade.

Adicionando mais links

---

_data/cards/es/clean-architecture.yaml
_data/cards/es/data-structures.yaml
_data/cards/es/django-rest-framework.yaml
_data/cards/es/django.yaml
_data/cards/es/flask.yaml
_data/cards/es/jupyter-and-colaboratory.yaml
_data/cards/es/oop-concepts.yaml
_data/cards/es/python-advanced-oop.yaml
_data/cards/es/python-api.yaml
_data/cards/es/python-args-kwargs.yaml
_data/cards/es/python-asynchronous.yaml
_data/cards/es/python-collections.yaml
_data/cards/es/python-dunder-methods.yaml
_data/cards/es/python-fundamentals.yaml
_data/cards/es/python-generators.yaml
_data/cards/es/python-lambdas-and-closures.yaml
_data/cards/es/python-metaprogramming.yaml
_data/cards/es/python-multiprocessing.yaml
_data/cards/es/python-mvc-mtv.yaml
_data/cards/es/python-static-typing.yaml
_data/cards/es/python-testing.yaml
_data/guides/es/python.yaml

Revert "Revert "Origin/python latam""

---

_data/guides/pt_BR/inteligencia-artificial.yaml

Adicionei cards opcionais no lado esquerdo do “T” de “Business e Serviços” para a carreira de "Inteligência Artificial”, mais especificamente os cards de “MLOps" e “Contêineres”.
- Por que adicionar MLOps?
Muitas vezes, não é possível simplesmente usar um modelo de Machine Learning treinado off-line como um serviço de previsão final. Frequentemente, é necessário um pipeline de múltiplas etapas para retreinar e implantar o modelo de forma contínua. Esse processo é complexo, pois automatiza tarefas que cientistas de dados fazem manualmente, como treinar e validar novos modelos antes de implantá-los.
- Por que adicionar Contêineres?
Um exemplo de implantação de modelos de Machine Learning em soluções de Platform-as-a-Service (PaaS) envolve o uso de contêineres Docker. Estes contêineres, …

feat: Adiciona cards de "MLOps" e "Contêineres" para carreia de IA

---

_data/cards/pt_BR/data-visualization.yaml
_data/cards/pt_BR/machine-learning-fundamentals.yaml
_data/cards/pt_BR/storytelling-with-data.yaml

Incluindo dois livros que podem contribuir para o processo de aprendizagem quando o estudante estiver nessa etapa.

Incluindo livros: "Machine Learning" e "Storytelling com dados"

---

_data/cards/pt_BR/kotlin-collections.yaml
_data/cards/pt_BR/kotlin-coroutines.yaml
_data/cards/pt_BR/kotlin-date-serialization.yaml
_data/cards/pt_BR/kotlin-errorhandling.yaml
_data/cards/pt_BR/kotlin-extensions.yaml
_data/cards/pt_BR/kotlin-fundamentals.yaml
_data/cards/pt_BR/kotlin-kdoc.yaml
_data/cards/pt_BR/kotlin-memory-management.yaml
_data/cards/pt_BR/kotlin-multiplatform.yaml
_data/cards/pt_BR/kotlin-scope-functions.yaml
_data/cards/pt_BR/kotlin-spring-boot.yaml
_data/cards/pt_BR/kotlin-type-safe-builders.yaml
_data/guides/pt_BR/kotlin-backend.yaml

Criação do Tech Guide de Kotlin

Tech guide de Kotlin

---

_data/cards/pt_BR/vue-composition-api.yaml
_data/cards/pt_BR/vue-options-api.yaml

- Artigo "Vue3: como declarar estados reativos";
- Artigo Alura "VueJS: ciclo de vida dos componentes.

Adiciona novos conteúdos na trilha de Vue

---

_data/cards/pt_BR/containers.yaml
_data/cards/pt_BR/data-engineering-fundamentals.yaml
_data/cards/pt_BR/data-lakes.yaml
_data/cards/pt_BR/data-pipelines-deploy.yaml
_data/cards/pt_BR/data-protection.yaml
_data/cards/pt_BR/data-warehouses.yaml
_data/cards/pt_BR/databases-fundamentals.yaml
_data/cards/pt_BR/design-patterns.yaml
_data/cards/pt_BR/infrastructure_as_code.yaml
_data/cards/pt_BR/log-management.yaml
_data/cards/pt_BR/mlops.yaml
_data/cards/pt_BR/nosql-databases.yaml
_data/cards/pt_BR/pipelines-and-etl.yaml
_data/cards/pt_BR/relational-databases.yaml
_data/cards/pt_BR/software_testing.yaml
_data/cards/pt_BR/streaming.yaml

Removemos links quebrados e adicionamos links novos nos cards: containers;data-engineering-fundamentals;data-lakes; data-pipelines-deploy;data-protection;data-arehouses;databases-fundamentals;design-patterns;infrastructure_as_code;log-management;mlops.

atualização data-engineering

---

_data/cards/pt_BR/android-ia.yaml
_data/cards/pt_BR/android-jetpack-compose-fundamentals.yaml
_data/cards/pt_BR/android-persistence.yaml
_data/guides/pt_BR/android.yaml

- Atualizando cartões de fundamentos do compose e persistência;
- Adicionando cartão para IA (Client-SDK e On-Device).

Atualizações guia de Android

---

_data/cards/pt_BR/business-analysis.yaml
_data/cards/pt_BR/communication-skills.yaml
_data/cards/pt_BR/data-modeling.yaml
_data/cards/pt_BR/data-visualization-bi.yaml
_data/cards/pt_BR/excel.yaml
_data/cards/pt_BR/power-bi.yaml
_data/cards/pt_BR/presentation-design.yaml
_data/cards/pt_BR/python-for-data-science.yaml
_data/cards/pt_BR/r-for-data-science.yaml
_data/cards/pt_BR/sql-advanced.yaml
_data/cards/pt_BR/sql-fundamentals.yaml
_data/cards/pt_BR/storytelling-with-data.yaml
_data/guides/pt_BR/business-intelligence.yaml

Eu faço parte da escola de dados e estou atualizando os cards do techguide de bi.

atualizando techguide de bi

---

_data/guides/pt_BR/kotlin-backend.yaml

Atualização do nome do arquivo `java-spring-framework`.

Atualização TechGuide Kotlin

---

_data/cards/pt_BR/first-contact-with-UX.yaml
_data/cards/pt_BR/ux-writing.yaml
_data/guides/pt_BR/ui-design.yaml

Ajuste para tentar arrumar erros visuais dos cards de ui e ux no techguide e atualização informações card de principios de UX

Atualização techguide: ajuste de nomes cards

---

_data/cards/pt_BR/design-system.yaml

Ajuste do nome Design Systems para design System no singular

Atualização techguide: Ajuste do nome Design Systems 

---

_data/cards/pt_BR/responsive-design.yaml

Vídeo privado do youtube removido.
Adicionado conteúdos de design responsivo: artigo, curso e 7DOC

feat: remove vídeo privado e adiciona novos conteúdos

---

_data/cards/pt_BR/javascript-accessibility.yaml

- Link da MDN atualizado
- Link da MDN sobre acessibilidade em HTML adicionado
- Link da formação de acessibilidade atualizado para a nova

fix: atualiza links

---

_data/cards/pt_BR/javascript-testing.yaml

- Links do Youtube da Alura privados foram removidos
- Adicionados novos conteúdos sobre testes: 2 artigos, 1 Alura+ e 2 podcasts

fix: remove links privados e adiciona novos conteúdos

---

_data/cards/pt_BR/javascript-modularization.yaml

- Removidos 2 artigos que focam em Node.js
- Adicionado 1 artigo que fala sobre modularização nativa de JavaScript

feat: remove 2 artigos e adiciona 1

---

_data/cards/pt_BR/javascript-errorhandling.yaml

- Adicionada página da documentação
- Adicionado artigo sobre tratamento de erros
- Atualizado link do curso

feat: adiciona conteúdos e atualiza link do curso

---

_data/cards/pt_BR/cloud-fundamentals.yaml
_data/cards/pt_BR/command-line-fundamentals.yaml
_data/cards/pt_BR/design-system.yaml
_data/cards/pt_BR/figma-fundamentals.yaml
_data/cards/pt_BR/http-fundamentals.yaml
_data/guides/pt_BR/android.yaml
_data/guides/pt_BR/angular.yaml
_data/guides/pt_BR/flutter.yaml
_data/guides/pt_BR/front-end.yaml
_data/guides/pt_BR/full-stack.yaml
_data/guides/pt_BR/ios.yaml
_data/guides/pt_BR/react.yaml
_data/guides/pt_BR/vue.yaml

Corrigindo erros dos cards complementares do guia.

Atualização Tech Guide Front-end (cards complementares)

---

_data/cards/pt_BR/big-data-fundamentals.yaml
_data/cards/pt_BR/business-process-management.yaml
_data/cards/pt_BR/computer-vision.yaml
_data/cards/pt_BR/data-engineering-fundamentals.yaml
_data/cards/pt_BR/data-visualization.yaml
_data/cards/pt_BR/deep-learning.yaml
_data/cards/pt_BR/feature-engineering.yaml
_data/cards/pt_BR/linear-and-logistic-regression.yaml
_data/cards/pt_BR/machine-learning-model-evaluation.yaml
_data/cards/pt_BR/machine-learning-unsupervised-learning.yaml
_data/cards/pt_BR/natural-language-processing.yaml
_data/cards/pt_BR/reinforcement-learning.yaml
_data/cards/pt_BR/statistical-tests.yaml
_data/cards/pt_BR/web-scraping.yaml
_data/guides/pt_BR/data-science.yaml

Estamos atualizando o TechGuide de Data Science.
Atualizamos alguns cards e também removemos e adicionamos alguns cards no guia.

Atualização do TechGuide de Data Science

---

_data/cards/pt_BR/Deep-dive-ux-research.yaml
_data/cards/pt_BR/Deep-dive-ux-strategy.yaml
_data/cards/pt_BR/Deep-dive-ux-writing.yaml
_data/cards/pt_BR/agile-culture.yaml
_data/cards/pt_BR/agile-frameworks.yaml
_data/cards/pt_BR/design-thinking.yaml
_data/cards/pt_BR/diving-in-ux-research.yaml
_data/cards/pt_BR/diving-in-ux-strategy.yaml
_data/cards/pt_BR/diving-in-ux-writing.yaml
_data/cards/pt_BR/product-management-fundamentals.yaml
_data/cards/pt_BR/starting-ux-research.yaml
_data/cards/pt_BR/starting-ux-strategy.yaml
_data/cards/pt_BR/starting-ux-writing.yaml
_data/cards/pt_BR/ux-documentation-and-portfolio.yaml
_data/cards/pt_BR/ux-interaction-strategy-and-design.yaml
_data/guides/pt_BR/UX_Design.yaml
_data/guides/pt_BR/agile.yaml

Atualizações no techguide de agilidade e primeiro comit com o techguide de UX design

Ux techguide

---

_data/cards/pt_BR/react-hooks-form.yaml

Olá, Tudo bem? 
Fiz a atualização desse guia de formulários com react e adicionei os conteúdos (novos cursos e artigos) da plataforma da Alura sobre o tema.

docs: Adiciona conteúdos da plataforma alura, como cursos e artigos

---

_data/cards/pt_BR/angular-testing.yaml

Adiciona novos conteúdos ao card de Angular testes no guia de Angular

docs: Adciona dois novos cursos de testes ao guia de Angular

---

_data/cards/pt_BR/android-ia.yaml

Adiciona um conteúdo de Android ao card de Android-ia

docs: Atualiza card do guia de android-ia

---

_data/cards/pt_BR/apollo-client.yaml
_data/cards/pt_BR/graphql.yaml

Adiciona novos conteúdos da plataforma Alura ao guia de React

docs: Adiciona curso de React query ao guia de React

---

_data/cards/pt_BR/solid.yaml

Adiciona novos conteúdos da plataforma Alura ao guia de Swift

docs: Adiciona curso de SOLID com IOS e Swift

---

_data/cards/pt_BR/swift-fundamentals.yaml

Adiciona novos conteúdos da plataforma Alura ao guia de Swift

docs: Adiciona artigo ao card de Swift Fundamentos

---

_data/cards/pt_BR/vue-components.yaml

Adiciona novos conteúdos da plataforma Alura ao guia de Vue.js

docs: Adiciona página pilar ao guia de Vue.js

---

_data/cards/pt_BR/ios-architecture.yaml

Adiciona novos conteúdos no card de IOS - Arquitetura
Obrigado pela revisão! Qualquer feedback é bem vindo!

docs: Adiciona conteúdo atualizado no card de ios arquitetura

---

_data/cards/pt_BR/ios-app-modularization.yaml

Adiciona artigo de Deeplinks ao card de IOS-Modularização no guia de IOS
Obrigado pela revisão! Qualquer feedback é bem vindo!

docs: Adiciona artigo de deeplinks ao card de IOS-modularização

---

_data/cards/pt_BR/ios-api.yaml

Adiciona conteúdo da plataforma Alura no card de IOS - Comunicação com API's
Obrigado pela revisão. Qualquer feedback é bem vindo!

docs: Atualiza o card de IOS - Comunicação com Api's

---

_data/cards/pt_BR/html-fundamentals.yaml

Adiciona um ALURA+ no guia de Front end
Obrigado pela revisão! Quaisquer feedbacks são bem vindos

docs: Adiciona um Alura+ sobre deploy na vercel no guia de Front-end

---

_data/downloadFiles/PT_BR/data-science.md
_data/guides/pt_BR/data-science.yaml

Acredito que seja importante então trazer o card para esse guia. 
Pela estrutura dele, acredito que no nível 3, assim como também se alinha com a nova formação de Data Science lançada na plataforma.

Adicionando card de previsões com séries temporais em data-science guide

---

_data/cards/pt_BR/flutter-packages.yaml

Adicionar artigo "Utilizando o Dio para comunicação com APIs"

Atualização "Flutter - Pacotes Essenciais"

---

_data/cards/pt_BR/advanced-data-analytics.yaml
_data/cards/pt_BR/data-lake-warehouse-architectures.yaml
_data/cards/pt_BR/data-pipelines-deploy.yaml
_data/guides/pt_BR/analytics-engineering.yaml

Criação de um guide para Engenharia de Analytics
Criação de 2 novos cards
E modificação em 1 card já existente

criando guide e cards para a carreira engenharia de analytics

---

_data/cards/pt_BR/agile-innovation.yaml
_data/cards/pt_BR/agility.yaml
_data/cards/pt_BR/ambidextrous-leadership.yaml
_data/cards/pt_BR/best-practices-as-a-habit.yaml
_data/cards/pt_BR/guiding-towards-high-performance.yaml
_data/cards/pt_BR/learning-about-leadership.yaml
_data/cards/pt_BR/management-practices-and-improvements.yaml
_data/cards/pt_BR/organizational-structure.yaml
_data/cards/pt_BR/public-speaking-for-leaders.yaml
_data/cards/pt_BR/techniques-and-skills-for-leadership.yaml
_data/cards/pt_BR/transformational-leadership.yaml
_data/cards/pt_BR/understanding-tech-leadership.yaml
_data/guides/pt_BR/lideranca.yaml

Cards em Lideranca em gestao e design

Att card Lideranca em gestao e design 

---

_data/cards/pt_BR/dart-fundamentals.yaml

Removi o curso de "Dart: criando e manipulando variáveis e listas", pois a versão atualizada já está neste Tech Guide, que seria o curso de "Dart: trabalhando com a sintaxe e configuração de projeto". Também adicionei a nova formação de "Dart: cursos para aprender a linguagem utilizada no Flutter".

Atualizando o Tech Guide de Dart fundamentos

---

_data/cards/pt_BR/accessibility-in-ux.yaml
_data/cards/pt_BR/design-thinking.yaml
_data/cards/pt_BR/introducing-ux-writing.yaml
_data/cards/pt_BR/nlp-qea-e-geracao-de-textos.yaml
_data/cards/pt_BR/starting-ux-writing.yaml
_data/cards/pt_BR/technical-writing.yaml
_data/guides/pt_BR/ux-writing.yaml

Atualizações em pastas referente a guide de UX Writing

att-ref-ux-writing

---

_data/downloadFiles/PT_BR/cloud.md

Correção de "diminiur" para "diminuir"
Correção de "ja" para "já"

Correção de erros de digitação e acentuação

---

_data/cards/pt_BR/css-fundamentals.yaml

Adicionando a nova formação de "CSS: cursos para transformar designs com Grid, Flexbox e Sass" que acabou de sair na plataforma.

Adicionando nova formação de CSS

---

_data/cards/pt_BR/react-architecture.yaml

Revert "Revert "feat: adicionando um novo cartão sobre arquitetura em React""

---

_data/guides/pt_BR/react.yaml

Revert "Revert "fix: corrigindo erros""

---

_data/cards/pt_BR/flutter-packages.yaml

Revert "feat: adicionando curso"

---

_data/cards/pt_BR/android-ia.yaml
_data/cards/pt_BR/flutter-persistence.yaml

- adicionar curso: "Android e OpenAI: integrando DALL-E, Whisper e GPT para áudios e imagens." em Android-IA
- adicionar formação: "Formação: domine aplicações offline-first com Flutter" em Flutter - Persistência de dados

Atualizar tech guide: escola front-end e mobile
