_data/blocks/javascript-modularization.pt_BR.yaml
No card de JavaScript - Modularização, os links para o youtube das opções: 
- Evandro Falleiros: Introdução à POO com JS - Modularização e importações
- Professor Edson Maia: JS OO Modularizar o código import e export
estavam redirecionando para um endereço icorreto.
=> correção de links no card de JavaScript - Modularização 

src/patterns/Footer/index.tsx, src/patterns/ScreenHeroContainer/patterns/SecondContentSection/index.tsx
Pequenas correções de espaçamento na home. A primeira é na section de discover, que atualmente está assim:
Com a correção, fica assim:
Quanto a correção no rodapé, foi apontado ao time de dev que o espaçamento do texto no mobile (especificamente tamanhos 390px) fica assim:
Com a correção, temos padding na direita também, impedindo que o texto fique grudado na aresta da página
=> Correções de espaçamento na home

.github/workflows/continuous-delivery.yml
Estava me baseando nos workflows definidos no projeto para configurar um projeto pessoal.
Vi que o último commit na `main` tinha a marcação do job `test` executado com referência pra ele, porém o arquivo `continuous-integration.yml` que configura o job `test` só acontece em PRs:
Depois de uns minutinhos entendi que era o nome do job de deploy que estava como `test`.
É um detalhe bem pequeno e simples mas que se corrigido evita que isso aconteça com outras pessoas.
=> Fix: nome do job no arquivo continuous-delivery.yml

src/components/Box/index.tsx, src/patterns/ScreenHeroContainer/patterns/FAQContentSection/index.tsx
#21 
Desktop
Mobile
Como estou escondendo o conteúdo apenas com `aria-hidden` e `height: 0`, os links que estão encolhidos dentro do FAQ ainda podem ser navegáveis por teclado, o que é meio estranho.
A solução mais simples pra isso seria abrir o acordeão caso o algum elemento focável dentro do acordeão fosse selecionado, mesmo com ele fechado. `onFocus={() => setIsOpen(true)}`, que foi o que fiz.
Se quisermos que os links sejam inacessíveis por teclado quando o acordeão estiver fechado precisamos gerenciar o estado da animação e quando ela terminar adicionar um `display: none` no conteúdo, mas eu acho que aumenta muito a complexidade do componente.
Que vocês acham?
=> style: efeito sanfona no FAQ mais suave

.vscode/extensions.json
Adiciona o arquivo `.vscode/extensions.json` ao projeto.
O Vscode lê esse arquivo e mostra um popup pra usuária que abra o projeto e não tenha as extensões instaladas. Isso na minha opinião melhora e experiência pra usuária que quer contribuir pro projeto pela primeira vez, e pode ajudar a evitar problemas como aconteceu no [PR#31](https://github.com/alura/techguide/pull/31#issuecomment-1248296637)
[Mais informações sobre o arquivo extensions.json](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)
=> Extensões recomendadas para VSCode

_data/blocks/angular-testing.pt_BR.yaml, _data/blocks/csharp-testing.pt_BR.yaml, _data/blocks/java-testing.pt_BR.yaml, _data/blocks/javascript-testing.pt_BR.yaml, _data/blocks/jest.pt_BR.yaml, _data/blocks/nodejs-testing.pt_BR.yaml, _data/blocks/php-testing.pt_BR.yaml, _data/blocks/python-testing.pt_BR.yaml
Fala pessoal! 
Queria deixar uma pequena contribuição com o projeto sugerindo a inclusão de um artigo que escrevi há pouco tempo sobre [Testes Unitários: Fundamentos e Qualidade de Software!](https://dev.to/wnqueiroz/testes-unitarios-fundamentos-e-qualidade-de-software-5af0).
A alteração adiciona o artigo nas seções de testes dentre os "paths" que acredito que faça sentido.
cc @omariosouto
=> Adicionar artigo agnóstico de testes unitários nas seções relacionadas à testes

_data/blocks/pt_BR/java-error-handling.pt_BR.yaml, _data/blocks/pt_BR/java-errorhandling.pt_BR.yaml
Removing a Javascript article link from the Java Error Handling Recommendation block
=> Removing a Javascript article link from Java Error Handling Recommendation block

_data/cards/pt_BR/jest.yaml
Submetendo revisão de link do vídeo de Matheus Castiglioni, card Jest, que apresentava referenciamento duplicado com o vídeo de Whashington Developer.
=> Correção de erro de referenciamento de link.

_data/guides/pt_BR/devops.yaml
Torna CSS opcional em DevOps, ja que o principal esta em "HTML - Fundamentos", retira uma tag opcional vazia de design-patterns
=> Optional CSS

_data/cards/pt_BR/vue-composition-api.yaml, _data/cards/pt_BR/vue-options-api.yaml
Adiciona artigo ["Vue3: Options API vs Composition API"](https://dev.to/sucodelarangela/vue3-options-api-vs-composition-api-1j09) aos guias "Vue - Options API" e "Vue - Composition API"
=> feat: add new article to vue content

_data/cards/pt_BR/react-webrouting.yaml, _data/cards/pt_BR/typescript-fundamentals.yaml
- Adicionei o curso [React: desenvolvendo em React Router com JavaScript](https://cursos.alura.com.br/course/React-desenvolvendo-react-router-javaScript): Este curso foi incluído para abordar o tópico de roteamento em React usando React Router com JavaScript, proporcionando aos nossos alunos uma compreensão mais profunda deste importante aspecto do desenvolvimento web em React.
- Adicionei a formação [TypeScript: desenvolva front-end com mais produtividade](https://cursos.alura.com.br/formacao-typescript-desenvolva-front-end-produtividade): Esta formação abrange os fundamentos do TypeScript e destina-se a melhorar a produtividade no desenvolvimento front-end com TypeScript.
Estas modificações visam melhorar nosso conteúdo …
=> feat: Adiciona conteúdos atualizados sobre os cards de react roteamento web e typescript

_data/cards/pt_BR/cypress.yaml, _data/cards/pt_BR/jest.yaml, _data/cards/pt_BR/react-testing-library.yaml
- Adicionei o curso [React JS: crie testes com Jest e Testing Library e garanta o funcionamento do Front-end](https://cursos.alura.com.br/course/react-js-testes-automatizados-front-end): Este curso oferece uma oportunidade valiosa para aprender a criar testes automatizados em React usando Jest e React Testing Library.
- Adicionei a formação [Melhore sua aplicação React com testes automatizados](https://cursos.alura.com.br/formacao-react-testes-automatizados): Esta formação aborda a importância dos testes automatizados em React e inclui cursos relevantes para aprimorar suas habilidades nessa área.
- Adicionei o curso [React: testando os seus componentes](https://cursos.alura.com.br/course/react-testando-componentes): Este …
=> feat: Adiciona cursos e formações referentes a testes com Testing Library, Jest e Cypress

_data/cards/pt_BR/linux-fundamentals.yaml
Corrigido link do Curso Linux II: programas, processos e pacotes, onde estava direcionando para a tela principal do alura e não para ao do curso
=> Corrigido link do Curso Linux II: programas, processos e pacotes, onde estava direcionando para a tela principal do alura e não para ao do curso

_data/cards/pt_BR/micro-frontend.yaml, _data/guides/pt_BR/front-end.yaml
Adicionei um card sobre Micro Frontends ao nosso guia de Frontend. Isso vai enriquecer nosso conteúdo visto que aproveitei para inserir os links dos cases que temos na plataforma com grandes empresas que usam essa solução nos seus negócios. Também faz parte de uma meta da escola de Frontend essa adição.
Por favor, revise e compartilhe qualquer feedback. Estou aberto a ajustes!
Alterações Propostas:
- Adiciona o card sobre Micro Frontends ao guia de Frontend.
Aguardando o seu feedback! 🚀
=> Adiciona o card de micro frontends no guia de Frontend

_data/guides/pt_BR/kotlin-backend.yaml
Card `java-functional-programming` não existe mais.
=> Correção de erros no Tech Guide de Kotlin

_data/guides/pt_BR/kotlin-backend.yaml
O card `test-driven-development` não existe mais.
=> Correção do Tech Guide de Kotlin

_data/cards/pt_BR/javascript-callbacks-promises.yaml
- Link introdutório da documentação do MDN movido para o início
- Link do curso de Node.js substituído pelo link do curso de Front-end
=> feat: organiza ordem dos links e atualiza link de curso

_data/cards/pt_BR/flutter-deployment.yaml, _data/cards/pt_BR/flutter-packages.yaml, _data/cards/pt_BR/flutter-testing.yaml
Adicionando a formação de CI/CD
Adicionando os artigos de CI/CD
Adicionando os dois cursos da formação em early access sobre pacotes essenciais (depois será atualizado para o link da formação)
Adicionando artigo sobre testes
=> Atualizando techguide de Flutter

_data/cards/pt_BR/adm-mongoDB.yaml, _data/cards/pt_BR/adm-mysql.yaml, _data/cards/pt_BR/adm-oracle-database.yaml, _data/cards/pt_BR/adm-postgreSQL.yaml, _data/cards/pt_BR/adm-sql-server.yaml, _data/cards/pt_BR/data-modeling.yaml, _data/cards/pt_BR/databases-fundamentals.yaml, _data/cards/pt_BR/mongoDB.yaml, _data/cards/pt_BR/mysql.yaml, _data/cards/pt_BR/operational-systems.yaml, _data/cards/pt_BR/oracle-database.yaml, _data/cards/pt_BR/postgreSQL.yaml, _data/cards/pt_BR/sql-server.yaml, _data/guides/pt_BR/database-administrator.yaml
Criação de um guide para Administração de Banco de Dados - DBA
Criação de 11 novos cards 
E modificação em 2 cards já existentes
=> Criação do guia Administração de Banco de Dados - DBA

_data/cards/pt_BR/ios-swiftui.yaml
Adiciona novos conteúdos da plataforma Alura no guia de Swift.
=> docs: Adiciona conteúdo sobre swiftUi no guia de iOS

_data/cards/pt_BR/service-workers.yaml
> **Descrição da PR**
Adiciona descrição ao card e conteúdos relevantes da plataforma Alura.
Desde já agradeço a colaboração e quaisquer alterações e sugestões são bem vindas.
Grande abraço!
=> Atualiza o card sobre service workers

_data/cards/pt_BR/dart-fundamentals.yaml
> Adiciona o artigo [Boas práticas do Dart para organizar um projeto](https://www.alura.com.br/artigos/boas-praticas-dart) no guia de Flutter. O conteúdo é fundamental para iniciantes na linguagem Dart e vai ajudar muito essas pessoas no avanço dos estudos em Flutter.
Desde já agradeço a colaboração e quaisquer alterações e sugestões são bem vindas.
Grande abraço!
=> Adiciona artigo de Dart no guide de Flutter

_data/cards/en_US/javascript-accessibility.yaml, _data/cards/es/javascript-accessibility.yaml, _data/cards/pt_BR/javascript-accessibility.yaml
Adiciona um novo recurso de acessibilidade aos cards para os 3 idiomas (português, inglês e espanhol). O recurso é um curso do web.dev (desenvolvedores do Chrome) que oferece valiosos insights e boas práticas para melhorar o desenvolvimento de acessibilidade na web.
=> Adicionando curso de acessibilidade do web.dev(desenvolvedores do Chrome)

_data/cards/pt_BR/ado-dot-net.yaml, _data/cards/pt_BR/asp-net-core.yaml, _data/cards/pt_BR/csharp-collections.yaml, _data/cards/pt_BR/csharp-memory-management.yaml, _data/cards/pt_BR/csharp-testing.yaml, _data/cards/pt_BR/data-structures.yaml, _data/cards/pt_BR/entity-framework-core.yaml, _data/cards/pt_BR/git-and-github-fundamentals.yaml, _data/cards/pt_BR/linq.yaml
Atualização dos Tech Guides da Escola de Programação incluindo conteúdos novos e removendo conteúdos que não estão mais disponíveis para acesso.
=> Jeniblodev patch 1

_data/cards/pt_BR/ado-dot-net.yaml, _data/cards/pt_BR/apollo-client.yaml, _data/cards/pt_BR/asp-net-core.yaml, _data/cards/pt_BR/clean-architecture.yaml, _data/cards/pt_BR/csharp-collections.yaml, _data/cards/pt_BR/csharp-memory-management.yaml, _data/cards/pt_BR/csharp-testing.yaml, _data/cards/pt_BR/data-structures.yaml, _data/cards/pt_BR/dependency-injection.yaml, _data/cards/pt_BR/django.yaml, _data/cards/pt_BR/entity-framework-core.yaml, _data/cards/pt_BR/git-and-github-fundamentals.yaml, _data/cards/pt_BR/graphql.yaml, _data/cards/pt_BR/java-build-tools.yaml, _data/cards/pt_BR/java-spring-boot.yaml, _data/cards/pt_BR/jvm.yaml, _data/cards/pt_BR/kotlin-fundamentals.yaml, _data/cards/pt_BR/linq.yaml, _data/cards/pt_BR/microservices.yaml, _data/cards/pt_BR/nestjs-fundamentals.yaml, _data/cards/pt_BR/nodejs-orm.yaml, _data/cards/pt_BR/nodejs-testing.yaml, _data/cards/pt_BR/php-api.yaml, _data/cards/pt_BR/php-collections.yaml, _data/cards/pt_BR/php-testing.yaml, _data/cards/pt_BR/python-dunder-methods.yaml, _data/cards/pt_BR/python-fundamentals.yaml, _data/cards/pt_BR/reflection-and-attributes.yaml, _data/cards/pt_BR/solid.yaml, _data/guides/pt_BR/csharp.yaml
Atualização de conteúdos dos Tech Guides da Escola de Programação, excluindo conteúdos indisponíveis, adicionando conteúdos complementares e corrigindo erros.
=> Atualização do Tech Guide Escola de Programação

_data/cards/pt_BR/react-state-management.yaml
Adicionando novo curso de Redux, artigo sobre Redux e formação de gerenciamento de estado e removendo uma formação duplicada sobre Context API e um curso de Zustand que está dentro da formação de gestão de estado adicionada.
=> feat: Adicionando novo curso, artigo e formação 

_data/cards/pt_BR/programming-logic.yaml, _data/guides/pt_BR/csharp.yaml, _data/guides/pt_BR/go.yaml, _data/guides/pt_BR/java.yaml, _data/guides/pt_BR/kotlin-backend.yaml, _data/guides/pt_BR/nodejs.yaml, _data/guides/pt_BR/php.yaml, _data/guides/pt_BR/python.yaml
Este PR cria novo card de conteúdo e adiciona esse novo card a alguns guias de back-end. 
Solicitação do PM da escola de programação.
Criando:
* `card` de conteúdo de lógica de programação com a formação de iniciante em programação
Adicionando:
* Card de lógica de programação aos `guides` de back-end (todas as linguagens)
=> add: conteúdo LP nos níveis JR de backend

_data/cards/pt_BR/shell-scripting.yaml
Estava acompanhando os conteúdos e percebi que o link do vídeo **NetworkChuck: BASH Scripting** estava duplicado e não existia a referência correta para o vídeo **Lucas Caton: Como criar scripts no Linux e no macOS**.
Adicionei o link que acredito ter sido recomendado. 😄
=> Corrigindo o link do vídeo do Lucas Caton
